[toolchain]
anchor_version = "0.30.1"

[programs.devnet]
ephemere = "4UxnYz4N5b5MnvMeGNqYGyvcu3izQYC7m6df9RhYTygo"

[programs.localnet]
ephemere = "4UxnYz4N5b5MnvMeGNqYGyvcu3izQYC7m6df9RhYTygo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -n import=tsx -t 1000000 tests/**/*.ts"
